### ISSUE TITLE
Segfault since last commit

### ISSUE THREAD

**Issue by HiPhish** [lewis6991/spellsitter.nvim#11]
Hello,

I just updated to the latest commit (c90bcc3564610ac29d52dc0019358e05832d37e4) and I have been getting segmentation faults in Neovim, at least with Python files. Not every Python file trips up the editor, so simple scripts are fine. I have attached a script which produces a segfault (I had to change the extension because of GitHub, change it back to `.py`):
[kNN.txt](https://github.com/lewis6991/spellsitter.nvim/files/6706486/kNN.txt)

**Comment by lewis6991** [comment]
I've noticed the same problem too, I'll need to investigate but will likely need to revert the last commit in some form.

**Comment by lewis6991** [comment]
The segfault came from `decoration.c` in nvim so I guess there is a bug in the extmark handling. The only thing changed in the last commit relating to this was to no longer use ephermal extmarks. https://github.com/lewis6991/spellsitter.nvim/commit/c1e9228630542336be6ad107fa380f138ec0e3c2 makes the extmarks ephemeral again so should resolve this. Please reopen otherwise.
